[theme]
primaryColor = "#4299e1"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7fafc"
textColor = "#2d3748"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
